<a href="https://colab.research.google.com/github/AwateNavnath/navnath/blob/main/Q3_Singular_Value_Decomposition_(SVD)_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Q3. Singular Value Decomposition (SVD):**

In [1]:
import numpy as np

np.random.seed(3)
A = np.random.randint(0, 10, size=(5, 5))

# Perform Singular Value Decomposition (SVD) on matrix A
U, Sigma, Vt = np.linalg.svd(A)
print("Matrix U:")
print(U)
print("\nMatrix Sigma (Diagonal matrix):")
print(np.diag(Sigma))
print("\nMatrix Vt (Transpose of V):")
print(Vt)
A_reconstructed = np.dot(U, np.dot(np.diag(Sigma), Vt))
print("\nIs A equal to the product of U, Sigma, and Vt? ", np.allclose(A, A_reconstructed))

# Rank 2 approximation of matrix A
rank_2_approximation = np.dot(U[:, :2], np.dot(np.diag(Sigma[:2]), Vt[:2, :]))
print("\nRank 2 approximation of matrix A:")
print(rank_2_approximation)

# Rank 3 approximation of matrix A
rank_3_approximation = np.dot(U[:, :3], np.dot(np.diag(Sigma[:3]), Vt[:3, :]))
print("\nRank 3 approximation of matrix A:")
print(rank_3_approximation)


Matrix U:
[[-6.21758204e-01  1.57221936e-01  1.68326958e-01  3.26582732e-01
  -6.73578320e-01]
 [-4.67670084e-01 -6.05520322e-01  7.65320935e-02 -6.39353120e-01
  -5.08686245e-04]
 [-3.41782064e-01  4.31365934e-01 -7.89806509e-01 -2.53152755e-01
   9.60615001e-02]
 [-4.15309576e-01  4.54663424e-01  5.20393697e-01 -6.49912786e-02
   5.88018418e-01]
 [-3.24660446e-01 -4.64576155e-01 -2.66842560e-01  6.45183015e-01
   4.37376858e-01]]

Matrix Sigma (Diagonal matrix):
[[26.78331252  0.          0.          0.          0.        ]
 [ 0.          9.76450342  0.          0.          0.        ]
 [ 0.          0.          6.18232967  0.          0.        ]
 [ 0.          0.          0.          3.09779547  0.        ]
 [ 0.          0.          0.          0.          0.70078979]]

Matrix Vt (Transpose of V):
[[-0.3823076  -0.52173478 -0.25046447 -0.49651275 -0.52189688]
 [ 0.58047978  0.46901398  0.03115728 -0.38781364 -0.54009158]
 [ 0.08195193  0.04290689 -0.6930067   0.6184649  -0.3587279